### ISSUE TITLE
Theme and color updates

### ISSUE THREAD

**Issue by kamwoods** [BitCurator/bitcurator-salt#16]
Updating a few things to make the theme better looking / more accessible for jammy in particular:

- Created a "terminal-profile-dark.txt" theme with a very dark shade (black pearl, #0E1B26) as background and the slightly larger Noto 12 font for readability. After spending a little more time with it I was finding the existing profile hard on the eyes.
- Added the original high-res xcf for the current base BitCurator logo to the /env/usr/share/bitcurator/resources/images, a png export of it, and 4K steel blue (#4682B4) wallpaper with the base BitCurator logo scaled and centered, BitCurator-Env4-Wallpaper.png. Appears to look better and resize nicely?

Maybe just disregard the old way completely and use the new wallpaper in both focal and jammy? I made a slight tweak to the gsettings so for now only focal gets the background color set and uses the old logo.

![Screenshot from 2022-09-26 17-27-18](https://user-images.githubusercontent.com/1088612/192385746-42cd5ffd-c5c9-4f11-9aff-9e81e94aa02f.png)

All in the branch UPDATE/theme.

**Comment by kamwoods** [comment]
Seems to work fine in focal as well. The rationale for the original setup was of course to keep the logo the same size irrespective of the resolution and avoid stretching/low quality zoom. But this isn't as significant a problem with the updated 4K wallpaper and current GNOME. The logo gets a *little* large on an ultrawidescreen equivalent, but otherwise fine.

**Comment by digitalsleuth** [comment]
That's great, I was just reviewing it as well. Did you want me to submit a PR with this?

**Comment by kamwoods** [comment]
Yes, if you wouldn't mind a quick sanity check. My pretty minor commits are in UPDATE/theme.

Also...probably everything in attic can just get deleted at this point? Recoverable from the repo if needed, but at this point I think it's just unused and never-to-be-used cruft.

**Comment by digitalsleuth** [comment]
Testing now, noticed that the bash script hadn't been updated to dconf load the terminal-profile-dark.txt so I've updated that. 
I'll remove everything in the attic in this PR as well.

**Comment by kamwoods** [comment]
Ah, sorry! And thanks.

**Comment by digitalsleuth** [comment]
Looked at the new terminal and it looks good. A slight variation on the color profile between the two (slightly different shades, possibly due to a missing palette. I'll look at creating a palette based on what you've created and add it to the config. I'll have that part done for tomorrow, but everything else is ready now. Submitting the PR.

**Comment by digitalsleuth** [comment]
Got the palette configured, but right now there are two options. Can you do the install of the latest release on both Focal and Jammy? The terminal palettes are slightly different (greens are brighter on Focal, smoother on Jammy, etc). Let me know which release is better and I'll grab the palette from that.

Also, I was thinking of a couple of other theme tweaks:
- Reduce the icon size in the dash-to-dock to 36
- possibly move the dock to the bottom vice left
- create a custom background color for the dock to match that of the background of the terminal, with 0.8 to 1.0 opacity (currently at 0.69, not very visible a difference).

Let me know what you think and I'll make it happen in the next PR.

**Comment by kamwoods** [comment]
Of note, I have a moderate color vision deficiency. The terminal background selection I made was basically "it's way down the shade chart from steel blue", and it might as well be black to me even on a color accurate monitor. Between the Jammy and Focal term defaults...maybe I prefer Jammy. I'd essentially just like the term background to remain dark-ish - beyond that, I'd defer to you to adjust any of the coloring and transparency as needed so nothing looks especially weird with the dock color in particular - I just can't necessarily always see it.

- Reduction of icon size is fine.
- I'd prefer to leave the dock on the left for the time being so that existing written docs and screenshots don't stray too far from the Ubuntu default.

I am meeting Wed afternoon with one of the Consortium committees to discuss various things, including the updates so far. Feedback and suggestions from others will likely follow (although probably not immediately).

**Comment by digitalsleuth** [comment]
Theme is almost finished. Making some minor tweaks which I think might bode well for the design. PR to come tonight!

**Comment by kamwoods** [comment]
Thanks, will keep an eye out for it!

**Comment by digitalsleuth** [comment]
Submitting the PR now, the changes I've made will show like the image below:

![JAMMY-FOCAL](https://user-images.githubusercontent.com/62841822/193296839-441b35ed-5b49-461f-881d-2a5281194d59.png)

- The dots which identify open programs, I've changed to dashes, and made them the same color blue as the background
- The color palette will now be the same no matter if it's Jammy or Focal
- The background color of the dock is now at 0.8 opacity, and is the same background color as the terminal, uniting the theme color (it doesn't look like it in the Focal image on the right, but that's due to the brightness in that VM)
- The icons are size 36 vice 48, freeing up a bit of space
- Removed the trash icon from the dock on Jammy (it shows up by default on Jammy, not on Focal)
- Changed the Menu icon to the BitCurator logo (bottom left) instead of the array of dots.

PR on its way!

**Comment by kamwoods** [comment]
After thinking about it, I think I would like to roll back one change before the next release: the replacement of the grid icon for "Show Applications" with the BitCurator logo. I can do this myself, but I wanted to present/discuss the rationale. In order of (roughly) most to least important:

- This presents a documentation issue; users referring to docs (ours, their own, from the web) may be reading things that refer to the "Grid Icon" (or looking at screenshots), and not immediately make the leap. It might seem like a small thing, but for new users, those who are not previously familiar with the Ubuntu UI, etc, it's additional, unneeded friction.
- Users who wish to return to the original icon cannot *easily* change it back, without digging into internals.
- Previously, BitCurator used this icon for several BitCurator-specific tools, which might be (if only briefly) confusing to some users.

I worry about UI tweaks that do not have a *very specific purpose* in particular because these changes may irk those who look to a degree of UI stability for documentation, training new hires, etc.

Everything else looks great.

**Comment by digitalsleuth** [comment]
Makes sense, and I completely understand. I have no problem rolling back the change, but I would like to present another point of view with a couple of thoughts:
- When it comes to building customized toolsets like these, it helps to have a full branding setup, including things like the 'start menu' icon. It demonstrates a forethought for dedication to a customized environment;
- Those who have never used Ubuntu before still get the concept of the 'start menu' or 'grid' usage, even if it's changed. In Windows XP we had the actual "Start" menu with the word written on it, and since then it's been an orb, and a flag, but the concept is still there from an operating system perspective: there's a button in a corner I have to press to give me a menu, let's click here;
- The documentation can easily be updated, and will already be updated to describe the new layout / tools / installation process, so updating it to demonstrate the BitCurator logo as the 'start menu' will take very little time to document;
- The idea of using the BitCurator logo for tools AND for the start menu is not an unheard of approach within the OS world, with variations of hard drive icons being used to demonstrate physical drives, networked drives, mounted USB drives, shared drive etc. Users that are using BitCurator should easily be able to identify a new icon within seconds, given the technical expertise they would already have if they're looking to use this toolset. A statement to this in a "README" or "Release Notes" would suffice to clarify that; and
- Since the majority of transactions through BitCurator will happen using the actual "Applications" menu at the top, and not the launcher, I think the change of the grid icon will likely have a minimal impact.

Again, I have no problem with changing the icon back, and see your point. I just wanted to provide a different point of view on the change.
I'll update the PR to roll back that one change, likely in the next 10 minutes!

**Comment by kamwoods** [comment]
Was away for a bit. Acknowledging all these points. For the time being let's consider a final decision on this as TBD, I'll merge and release, send the development committee (includes active users) some notes, and get additional feedback. I expect there will be some other changes requested in the coming weeks, so there will be an opportunity to revisit without too much delay.

**Comment by kamwoods** [comment]
Closing this now as the bulk of the fixes are in release. Will reopen after community feedback if icon change (other branding changes possibly?) are approved or suggested.
