### ISSUE TITLE
upgrade fails due to legacy directory

### ISSUE THREAD

**Issue by DasFaultier** [BitCurator/bitcurator-salt#32]
Hi,

while upgrading from Bitcurator 2.2.2 to 4.4.1, I noticed a bug in the installation routine.

I ran `sudo bitcurator upgrade` and during the upgrade routine, the setup failed complaining that there was already a directory located at a path that the setup tried to put a symlink. 

I resolved the issue by running `sudo mv /usr/share/regripper/plugins /usr/share/regripper/plugins_BAK` (effectively moving the directoryout of the way while retaining a backup) and rerunning `sudo bitcurator upgrade`.  After that, the setup finished successfully.

To make the setup more robust, I recommend removing the existing directory before creating the symlink.

**Comment by kamwoods** [comment]
Hi @DasFaultier,

2.x.x to 4.x.x upgrades are not recommended/supported due to the significant changes in the installer, salt states, and underlying tools. Even though this is the only "install stopping" issue such an upgrade produces (I just tested in with 2.2.24/upgraded to 20.04 -> 4.4.1 out of curiosity), there's a lot of other weirdness and cruft left over - the desktop folders and links that no longer work, old BitCurator tools that have been end-of-life'd left in /usr/local/bin, probably other things as well.

Regripper states, install locations, and symlinks are consistent across 4.x.x -> 4.x.x upgrades, and do not produce this error, so I'm inclined to say this particular issue is a "won't fix".

**Comment by kantonelli** [comment]
In this case, if you still want to move to 4.x.x, is there a best way to fully uninstall 2.x.x and start fresh?

**Comment by kamwoods** [comment]
There is no uninstall method available for 2.x.x. The 4.x.x releases should be installed on a new 22.04LTS or 20.04LTS Ubuntu base.

**Comment by digitalsleuth** [comment]
@kantonelli Has this issue been resolved for you?

**Comment by kamwoods** [comment]
Closing now as no further development or support for 2.x.x upgrades is planned and no additional comments posted.
